---
- hosts: satellite-server
  roles:
    - role: volumes
    - role: ntp
      ntp_server:
        - '169.254.169.123'
    - role: satellite-deployment
  vars_files:
    - "{{ satellite_deployment_vars }}"
